from typing import Any, Sequence

class LogisticRegression:
    classes_: Sequence[int]
    def __init__(self, *, max_iter: int = ..., random_state: int | None = ...) -> None: ...
    def fit(self, X: Any, y: Sequence[int]) -> LogisticRegression: ...
    def predict_proba(self, X: Any) -> Any: ...
