"""Canonical Firestore collection and subcollection names."""

USERS_COLLECTION = "users"
USERNAMES_COLLECTION = "usernames"

BILLING_SUBCOLLECTION = "billing"
BILLING_DOCUMENT_ID = "main"
AI_CREDITS_SUBCOLLECTION = "aiCredits"
AI_CREDITS_CURRENT_DOCUMENT_ID = "current"
AI_CREDIT_TRANSACTIONS_SUBCOLLECTION = "aiCreditTransactions"

MEALS_SUBCOLLECTION = "meals"
MY_MEALS_SUBCOLLECTION = "myMeals"
BADGES_SUBCOLLECTION = "badges"
STREAK_SUBCOLLECTION = "streak"
CHAT_THREADS_SUBCOLLECTION = "chat_threads"
MESSAGES_SUBCOLLECTION = "messages"
FEEDBACK_SUBCOLLECTION = "feedback"
NOTIFICATIONS_SUBCOLLECTION = "notifications"
PREFS_SUBCOLLECTION = "prefs"

RATE_LIMITS_COLLECTION = "rate_limits"
AI_RUNS_COLLECTION = "ai_runs"
MEMORY_SUBCOLLECTION = "memory"
